//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMP1124M_Assignment_2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMP1124M_Assignment_2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.8614 
        ///
        ///15.3207 
        ///
        ///18.3596 
        ///
        ///17.1516 
        ///
        ///15.5238 
        ///
        ///18.4468 
        ///
        ///19.2638 
        ///
        ///17.0751 
        ///
        ///17.2337 
        ///
        ///18.2691 
        ///
        ///23.2390 
        ///
        ///18.5899 
        ///
        ///15.3326 
        ///
        ///19.6179 
        ///
        ///17.6234 
        ///
        ///21.1611 
        ///
        ///18.7530 
        ///
        ///16.1001 
        ///
        ///20.2613 
        ///
        ///16.4009 
        ///
        ///19.1440 
        ///
        ///18.9225 
        ///
        ///18.0293 
        ///
        ///18.5464 
        ///
        ///14.2880 
        ///
        ///18.8349 
        ///
        ///19.1575 
        ///
        ///16.9244 
        ///
        ///17.8536 
        ///
        ///18.5795 
        ///
        ///19.4556 
        ///
        ///20.2828 
        ///
        ///16.4306 
        ///
        ///17.9638 
        ///
        ///19.5932 
        ///
        ///19.7682 
        ///
        ///15.8855 
        ///
        ///14.1541 
        ///
        ///18.0018 
        ///
        ///17.9176 
        ///
        ///15.6362 
        ///
        ///16.2081 
        ///
        ///18.4545 
        ///
        ///18.0560 
        ///
        ///19.2893 
        ///
        ///18.5476 
        ///
        ///19.743 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string High_2048 {
            get {
                return ResourceManager.GetString("High_2048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.9907 
        ///
        ///18.5027 
        ///
        ///17.4430 
        ///
        ///20.1179 
        ///
        ///20.4681 
        ///
        ///18.0841 
        ///
        ///20.3594 
        ///
        ///18.9854 
        ///
        ///15.1613 
        ///
        ///19.4529 
        ///
        ///22.7035 
        ///
        ///18.9804 
        ///
        ///16.1789 
        ///
        ///20.5424 
        ///
        ///16.4096 
        ///
        ///17.0089 
        ///
        ///20.3299 
        ///
        ///16.6420 
        ///
        ///17.3012 
        ///
        ///17.9830 
        ///
        ///19.1601 
        ///
        ///19.5663 
        ///
        ///19.9917 
        ///
        ///20.7712 
        ///
        ///15.2285 
        ///
        ///16.5610 
        ///
        ///20.6313 
        ///
        ///18.5511 
        ///
        ///14.0507 
        ///
        ///18.7088 
        ///
        ///19.2744 
        ///
        ///22.0431 
        ///
        ///18.6620 
        ///
        ///17.3561 
        ///
        ///17.6448 
        ///
        ///22.2294 
        ///
        ///18.7756 
        ///
        ///14.5472 
        ///
        ///16.7682 
        ///
        ///16.1711 
        ///
        ///14.3298 
        ///
        ///20.1067 
        ///
        ///15.7163 
        ///
        ///14.8684 
        ///
        ///20.3592 
        ///
        ///17.4959 
        ///
        ///15.903 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string High_256 {
            get {
                return ResourceManager.GetString("High_256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.6511 
        ///
        ///18.0779 
        ///
        ///17.2627 
        ///
        ///19.6661 
        ///
        ///15.9949 
        ///
        ///15.9744 
        ///
        ///17.4637 
        ///
        ///15.2669 
        ///
        ///20.0663 
        ///
        ///16.5341 
        ///
        ///16.1577 
        ///
        ///19.5708 
        ///
        ///21.6472 
        ///
        ///18.7447 
        ///
        ///20.8605 
        ///
        ///18.5488 
        ///
        ///21.5290 
        ///
        ///15.4814 
        ///
        ///15.4595 
        ///
        ///20.7466 
        ///
        ///20.2272 
        ///
        ///18.2885 
        ///
        ///14.1835 
        ///
        ///21.1131 
        ///
        ///18.3952 
        ///
        ///19.5308 
        ///
        ///17.1066 
        ///
        ///17.1708 
        ///
        ///20.6644 
        ///
        ///22.0334 
        ///
        ///19.7242 
        ///
        ///17.3989 
        ///
        ///20.1876 
        ///
        ///18.4060 
        ///
        ///21.1671 
        ///
        ///17.8520 
        ///
        ///18.7645 
        ///
        ///18.1334 
        ///
        ///19.2979 
        ///
        ///17.1612 
        ///
        ///19.6044 
        ///
        ///19.7427 
        ///
        ///16.2325 
        ///
        ///18.0684 
        ///
        ///16.2426 
        ///
        ///17.8081 
        ///
        ///19.189 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string High_4096 {
            get {
                return ResourceManager.GetString("High_4096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -0.9433 
        ///
        ///-7.9346 
        ///
        ///-5.2971 
        ///
        ///-3.1362 
        ///
        ///-3.4837 
        ///
        ///-3.7761 
        ///
        ///-1.2904 
        ///
        ///0.4923 
        ///
        ///-1.0240 
        ///
        ///-4.2380 
        ///
        ///-2.5725 
        ///
        ///0.6669 
        ///
        ///-1.2296 
        ///
        ///-1.5638 
        ///
        ///-4.2017 
        ///
        ///-4.7007 
        ///
        ///-3.3268 
        ///
        ///-0.4115 
        ///
        ///-4.1471 
        ///
        ///-1.7764 
        ///
        ///-4.0395 
        ///
        ///0.1871 
        ///
        ///-5.5777 
        ///
        ///-1.5036 
        ///
        ///-1.8980 
        ///
        ///-2.8149 
        ///
        ///-7.0758 
        ///
        ///-1.8795 
        ///
        ///-3.3166 
        ///
        ///-1.4390 
        ///
        ///-2.6046 
        ///
        ///-0.9061 
        ///
        ///-3.9315 
        ///
        ///-7.3013 
        ///
        ///-1.3232 
        ///
        ///2.9973 
        ///
        ///-4.2967 
        ///
        ///-6.5863 
        ///
        ///-1.6977 
        ///
        ///-4.5009 
        ///
        ///-3.2231 
        ///
        ///-2.2751 
        ///
        ///0.4146 
        ///
        ///-2.0391 
        ///
        ///0.5931 
        ///
        ///-1.3845 
        ///
        ///0.3768 
        ///
        ///-3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Low_2048 {
            get {
                return ResourceManager.GetString("Low_2048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -2.2634 
        ///
        ///2.6365 
        ///
        ///-7.9489 
        ///
        ///-2.2483 
        ///
        ///0.7006 
        ///
        ///-2.4439 
        ///
        ///-1.8669 
        ///
        ///-4.3792 
        ///
        ///-6.9052 
        ///
        ///-1.5640 
        ///
        ///0.1418 
        ///
        ///-0.6509 
        ///
        ///-3.0090 
        ///
        ///-2.6039 
        ///
        ///0.6687 
        ///
        ///-6.3607 
        ///
        ///-1.0610 
        ///
        ///-2.6556 
        ///
        ///-4.7127 
        ///
        ///-1.4680 
        ///
        ///-4.0053 
        ///
        ///-1.9198 
        ///
        ///-4.0521 
        ///
        ///-4.7408 
        ///
        ///1.9737 
        ///
        ///-3.4661 
        ///
        ///-1.6033 
        ///
        ///-1.2864 
        ///
        ///-3.1604 
        ///
        ///-5.9168 
        ///
        ///-4.1147 
        ///
        ///1.4052 
        ///
        ///-1.4533 
        ///
        ///-5.7830 
        ///
        ///-0.1022 
        ///
        ///-2.4485 
        ///
        ///-0.6426 
        ///
        ///-5.5326 
        ///
        ///3.1389 
        ///
        ///-4.0468 
        ///
        ///-6.3009 
        ///
        ///-1.5078 
        ///
        ///-4.1644 
        ///
        ///-3.3560 
        ///
        ///-4.1052 
        ///
        ///-7.5488 
        ///
        ///-3.2744 
        ///
        ///-1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Low_256 {
            get {
                return ResourceManager.GetString("Low_256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -5.2453 
        ///
        ///-5.2524 
        ///
        ///0.6037 
        ///
        ///1.6467 
        ///
        ///-3.5253 
        ///
        ///-0.7038 
        ///
        ///-1.2810 
        ///
        ///-0.4607 
        ///
        ///-3.4536 
        ///
        ///-2.1551 
        ///
        ///-0.0869 
        ///
        ///-5.5848 
        ///
        ///-4.2818 
        ///
        ///-3.5298 
        ///
        ///-2.6895 
        ///
        ///-5.7273 
        ///
        ///-3.0298 
        ///
        ///-0.4996 
        ///
        ///-5.5123 
        ///
        ///-1.9142 
        ///
        ///-3.6703 
        ///
        ///-3.2211 
        ///
        ///-4.0198 
        ///
        ///-2.0675 
        ///
        ///-4.5865 
        ///
        ///-2.4676 
        ///
        ///0.1298 
        ///
        ///-4.4804 
        ///
        ///-2.7302 
        ///
        ///-0.4615 
        ///
        ///-3.5524 
        ///
        ///-6.5338 
        ///
        ///-3.7657 
        ///
        ///-5.4371 
        ///
        ///-3.4289 
        ///
        ///-4.4248 
        ///
        ///-4.1219 
        ///
        ///-1.4399 
        ///
        ///-1.8698 
        ///
        ///-1.5642 
        ///
        ///-2.8950 
        ///
        ///-5.1980 
        ///
        ///-1.4449 
        ///
        ///-5.9920 
        ///
        ///-1.2937 
        ///
        ///-1.7483 
        ///
        ///-1.4011         /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Low_4096 {
            get {
                return ResourceManager.GetString("Low_4096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.5784 
        ///
        ///5.6036 
        ///
        ///10.0765 
        ///
        ///9.3148 
        ///
        ///9.7205 
        ///
        ///5.3045 
        ///
        ///7.4876 
        ///
        ///6.5473 
        ///
        ///6.9855 
        ///
        ///8.8105 
        ///
        ///7.3027 
        ///
        ///7.1208 
        ///
        ///10.2386 
        ///
        ///3.1045 
        ///
        ///6.7103 
        ///
        ///6.7227 
        ///
        ///8.1921 
        ///
        ///6.1873 
        ///
        ///8.0204 
        ///
        ///7.9345 
        ///
        ///6.9891 
        ///
        ///7.4961 
        ///
        ///9.5024 
        ///
        ///10.8394 
        ///
        ///4.8823 
        ///
        ///8.9669 
        ///
        ///10.3938 
        ///
        ///5.8048 
        ///
        ///5.3991 
        ///
        ///7.9798 
        ///
        ///5.5081 
        ///
        ///5.1004 
        ///
        ///7.3285 
        ///
        ///6.4185 
        ///
        ///8.3731 
        ///
        ///7.3097 
        ///
        ///10.6449 
        ///
        ///7.3267 
        ///
        ///6.9729 
        ///
        ///8.4625 
        ///
        ///8.7115 
        ///
        ///8.6651 
        ///
        ///8.5498 
        ///
        ///6.0460 
        ///
        ///10.2723 
        ///
        ///12.1941 
        ///
        ///8.8629 
        ///
        ///9.5765 
        ///
        ///8.6159 
        ///
        ///6.8613 
        ///
        ///8.178 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mean_2048 {
            get {
                return ResourceManager.GetString("Mean_2048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.6987 
        ///
        ///6.2994 
        ///
        ///7.4167 
        ///
        ///8.4069 
        ///
        ///13.8266 
        ///
        ///6.4359 
        ///
        ///4.2538 
        ///
        ///6.7373 
        ///
        ///9.7480 
        ///
        ///8.7380 
        ///
        ///9.6247 
        ///
        ///7.9933 
        ///
        ///8.7371 
        ///
        ///10.3482 
        ///
        ///10.9695 
        ///
        ///8.3196 
        ///
        ///6.8819 
        ///
        ///2.9812 
        ///
        ///13.5785 
        ///
        ///8.1117 
        ///
        ///9.9080 
        ///
        ///8.4021 
        ///
        ///6.5864 
        ///
        ///7.2051 
        ///
        ///6.0899 
        ///
        ///10.5068 
        ///
        ///6.5165 
        ///
        ///7.6924 
        ///
        ///10.4860 
        ///
        ///10.0831 
        ///
        ///8.6387 
        ///
        ///6.3335 
        ///
        ///6.4227 
        ///
        ///7.8469 
        ///
        ///5.8327 
        ///
        ///8.3511 
        ///
        ///9.4856 
        ///
        ///7.7133 
        ///
        ///6.8635 
        ///
        ///9.0230 
        ///
        ///7.9578 
        ///
        ///8.8542 
        ///
        ///6.4048 
        ///
        ///11.2061 
        ///
        ///6.8092 
        ///
        ///9.1296 
        ///
        ///3.8278 
        ///
        ///7.7098 
        ///
        ///6.9655 
        ///
        ///7.6495 
        ///
        ///7.51 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mean_256 {
            get {
                return ResourceManager.GetString("Mean_256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.4421 
        ///
        ///7.5537 
        ///
        ///8.4567 
        ///
        ///6.1291 
        ///
        ///7.7166 
        ///
        ///6.1754 
        ///
        ///10.7675 
        ///
        ///6.6622 
        ///
        ///5.7641 
        ///
        ///6.2371 
        ///
        ///9.8292 
        ///
        ///4.7173 
        ///
        ///9.5472 
        ///
        ///8.2566 
        ///
        ///7.3733 
        ///
        ///10.0012 
        ///
        ///10.6249 
        ///
        ///7.6744 
        ///
        ///10.0510 
        ///
        ///5.8636 
        ///
        ///7.4098 
        ///
        ///5.0118 
        ///
        ///7.7622 
        ///
        ///7.0814 
        ///
        ///6.5312 
        ///
        ///7.5727 
        ///
        ///8.7881 
        ///
        ///8.6791 
        ///
        ///9.2708 
        ///
        ///5.6256 
        ///
        ///6.8133 
        ///
        ///7.4279 
        ///
        ///8.6496 
        ///
        ///9.9819 
        ///
        ///8.5667 
        ///
        ///7.0472 
        ///
        ///10.4282 
        ///
        ///10.7573 
        ///
        ///8.4871 
        ///
        ///10.6885 
        ///
        ///9.6773 
        ///
        ///6.6704 
        ///
        ///6.2178 
        ///
        ///5.9801 
        ///
        ///9.8789 
        ///
        ///9.1750 
        ///
        ///6.0686 
        ///
        ///7.6376 
        ///
        ///8.1162 
        ///
        ///10.0537 
        ///
        ///11.7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mean_4096 {
            get {
                return ResourceManager.GetString("Mean_4096", resourceCulture);
            }
        }
    }
}
